# Generated by Django 3.1.6 on 2021-02-16 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0002_auto_20210216_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingsession',
            name='weights_file',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
