# Generated by Django 3.1.6 on 2021-02-16 15:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0003_auto_20210216_0228'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsession',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
