# Generated by Django 3.1.6 on 2021-02-16 15:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0004_trainingsession_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingsession',
            name='id',
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
