# Generated by Django 3.1.6 on 2021-02-16 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0007_auto_20210216_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsession',
            name='scaler_file',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
