# Generated by Django 3.1.6 on 2021-02-16 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0008_trainingsession_scaler_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingsession',
            name='weights_file',
        ),
    ]
