# Generated by Django 3.1.6 on 2021-02-16 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0009_remove_trainingsession_weights_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingsession',
            name='scaler_file',
        ),
    ]
