# Generated by Django 3.1.6 on 2021-02-16 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0010_remove_trainingsession_scaler_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingsession',
            name='training_history',
            field=models.JSONField(blank=True, default={}, null=True),
        ),
    ]
