# Generated by Django 3.1.6 on 2021-02-16 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0011_auto_20210216_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingsession',
            name='test_dates',
            field=models.JSONField(blank=True, default=[], null=True),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='training_dates',
            field=models.JSONField(blank=True, default=[], null=True),
        ),
    ]
