# Generated by Django 3.1.6 on 2021-02-16 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0013_auto_20210216_1806'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockPrediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateTimeField(db_index=True)),
                ('prediction', models.DecimalField(decimal_places=10, max_digits=19, null=True)),
                ('training_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predictor.trainingsession')),
            ],
            options={
                'unique_together': {('training_session', 'dt')},
            },
        ),
    ]
