# Generated by Django 3.1.6 on 2021-02-17 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0014_stockprediction'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockprediction',
            name='actual',
            field=models.DecimalField(decimal_places=10, max_digits=19, null=True),
        ),
    ]
