# Generated by Django 3.1.6 on 2021-02-25 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0018_lendingrate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lendingrate',
            options={'ordering': ['dt']},
        ),
    ]
