# Generated by Django 3.1.6 on 2021-02-28 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0019_auto_20210225_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='lendingrate',
            name='term',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='lendingrate',
            unique_together={('platform', 'coin', 'dt', 'term')},
        ),
    ]
